###Test Post method with empty Body
POST http://localhost:8080/api/auth/register

###Test Post method with Invalid(Size < 6) Body
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "dummy",
  "password": "dummy"
}

###Test post method with Invalid(no email) Body
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "dummy_account",
  "password": "dummy_password"
}


###Test post method with Invalid Email Body
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "dummy@",
  "username": "dummy_account",
  "password": "dummy_password"
}

###Test Post method with Valid Email Body
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "dummy@example.com",
  "username": "dummy_account",
  "password": "dummy_password"
}

###Test Post method with Valid Body
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "dummy_account",
  "password": "dummy_password"
}

###Test Post method with Valid Body
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "vanduc",
  "password": "vanduc1234"
}

###Test Authorize
GET http://localhost:8080/api/check/user
